
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dc-countdown-dev
    volumes:
      # Mount entire project directory for hot reload
      - .:/usr/src/app
      # Use container's node_modules
      - /usr/src/app/node_modules
      # Persist database between restarts
      - db-data:/usr/src/app/data
      # Persist uploads between restarts
      - uploads-data:/usr/src/app/uploads
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_PATH=/usr/src/app/data/migration.db
    restart: unless-stopped
    command: nodemon --watch . --ext js,json,html,css --ignore '*.db' --ignore 'uploads/*' server.js
    networks:
      - dc-network
    # Remove external port mapping since nginx will proxy
    expose:
      - "3000"

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'     # Public HTTP Port
      - '443:443'   # Public HTTPS Port
      - '81:81'     # Admin Web Port
    volumes:
      - nginx-data:/data
      - nginx-letsencrypt:/etc/letsencrypt
    networks:
      - dc-network
    environment:
      # Uncomment to disable IPV6
      DISABLE_IPV6: 'true'

networks:
  dc-network:
    driver: bridge

volumes:
  db-data:
  uploads-data:
  nginx-data:
  nginx-letsencrypt:
